name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  camera_bg:
    path: ../
  flutter:
    sdk: flutter
  flutter_foreground_task: ^3.7.3
  path_provider: ^2.0.0
  permission_handler: ^9.2.0
  video_player: ^2.1.4
  flutter_overlay_window: ^0.2.9
  bg_launcher:
    git:
      url: git@github.com:X-SLAYER/bg_launcher.git

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
